//
//  Brand.swift
//  Brandr
//
//  Created by Quinn McHenry on 11/5/21.
//

import SwiftUI
import DynamicColor

struct Brand {
    let name: String
    let background: Color
    let foreground: Color
    let font: Font
}

extension Brand {
    init(name: String) {
        let background = DynamicColor.random()
        self.name = name
        self.background = Color(background)
        self.foreground = background.isLight() ? .black : .white
        self.font = Font.random()
    }
}

extension Font {
    static func random() -> Font {
        Font.custom(allFonts.randomElement() ?? "Comic Sanz", size: 24)
    }
}

extension DynamicColor {
    static func random() -> DynamicColor {
        DynamicColor(hue: CGFloat.random(in: 0...360), saturation: CGFloat.random(in: 0.164...0.3828), lightness: CGFloat.random(in: 0.156...0.8515))
    }
}

fileprivate let allFonts = [
    "AcademyEngravedLetPlain",
    "AlNile-Bold",
    "AmericanTypewriter-Bold",
    "AmericanTypewriter-Light",
    "AppleSDGothicNeo-Light",
    "AppleSDGothicNeo-Thin",
    "Arial-BoldItalicMT",
    "Arial-ItalicMT",
    "ArialHebrew-Light",
    "Avenir-BlackOblique",
    "Avenir-Oblique",
    "Avenir-Roman",
    "AvenirNext-HeavyItalic",
    "AvenirNext-Italic",
    "AvenirNext-UltraLightItalic",
    "AvenirNextCondensed-HeavyItalic",
    "AvenirNextCondensed-Italic",
    "AvenirNextCondensed-UltraLightItalic",
    "Barlow-Bold",
    "Barlow-Medium",
    "Baskerville-Italic",
    "Baskerville-SemiBoldItalic",
    "BodoniSvtyTwoITCTT-BookIta",
    "BodoniSvtyTwoOSITCTT-BookIt",
    "ChalkboardSE-Light",
    "Charter-BoldItalic",
    "Charter-Italic",
    "Cochin-BoldItalic",
    "Cochin-Italic",
    "Copperplate-Light",
    "CourierNewPS-BoldItalicMT",
    "CourierNewPS-ItalicMT",
    "DamascusLight",
    "DamascusSemiBold",
    "DevanagariSangamMN-Bold",
    "Didot-Italic",
    "EuphemiaUCAS-Italic",
    "Futura-CondensedMedium",
    "Futura-MediumItalic",
    "Galvji-Bold",
    "GeezaPro-Bold",
    "Georgia-BoldItalic",
    "Georgia-Italic",
    "GillSans-Italic",
    "GillSans-LightItalic",
    "GranthaSangamMN-Bold",
    "Helvetica-LightOblique",
    "Helvetica-Oblique",
    "HelveticaNeue-Italic",
    "HelveticaNeue-UltraLightItalic",
    "HoeflerText-BlackItalic",
    "HoeflerText-Italic",
    "Kailasa-Bold",
    "KohinoorBangla-Light",
    "KohinoorDevanagari-Light",
    "KohinoorGujarati-Light",
    "KohinoorTelugu-Light",
    "Lora-Bold",
    "Lora-Medium",
    "MalayalamSangamMN-Bold",
    "MarkerFelt-Wide",
    "Menlo-BoldItalic",
    "Menlo-Italic",
    "MuktaMahee-Light",
    "MyanmarSangamMN-Bold",
    "Noteworthy-Bold",
    "NotoNastaliqUrdu-Bold",
    "NotoSansKannada-Light",
    "NotoSansMyanmar-Light",
    "NotoSansOriya-Bold",
    "Optima-BoldItalic",
    "Optima-Italic",
    "Palatino-BoldItalic",
    "Palatino-Italic",
    "Papyrus-Condensed",
    "PingFangHK-Light",
    "PingFangHK-Ultralight",
    "PingFangSC-Light",
    "PingFangSC-Ultralight",
    "PingFangTC-Light",
    "PingFangTC-Ultralight",
    "Rockwell-BoldItalic",
    "Rockwell-Italic",
    "SinhalaSangamMN-Bold",
    "SnellRoundhand-Bold",
    "TamilSangamMN-Bold",
    "Thonburi-Light",
    "TimesNewRomanPS-BoldItalicMT",
    "TimesNewRomanPS-ItalicMT",
    "Trebuchet-BoldItalic",
    "TrebuchetMS-Italic",
    "Verdana-BoldItalic",
    "Verdana-Italic",
    "AlNile",
    "AmericanTypewriter",
    "AppleColorEmoji",
    "AppleSDGothicNeo-Regular",
    "AppleSymbols",
    "ArialHebrew",
    "ArialMT",
    "ArialRoundedMTBold",
    "Avenir-Book",
    "AvenirNext-Regular",
    "AvenirNextCondensed-Regular",
    "Barlow-Regular",
    "Baskerville",
    "BodoniOrnamentsITCTT",
    "BodoniSvtyTwoITCTT-Book",
    "BodoniSvtyTwoOSITCTT-Book",
    "BodoniSvtyTwoSCITCTT-Book",
    "BradleyHandITCTT-Bold",
    "ChalkboardSE-Regular",
    "Chalkduster",
    "Charter-Roman",
    "Cochin",
    "Copperplate",
    "CourierNewPSMT",
    "Damascus",
    "DevanagariSangamMN",
    "Didot",
    "DINAlternate-Bold",
    "DINCondensed-Bold",
    "DiwanMishafi",
    "EuphemiaUCAS",
    "Farah",
    "Futura-Medium",
    "Galvji",
    "GeezaPro",
    "Georgia",
    "GillSans",
    "GranthaSangamMN-Regular",
    "Helvetica",
    "HelveticaNeue",
    "HiraginoSans-W3",
    "HiraginoSans-W6",
    "HiraMaruProN-W4",
    "HiraMinProN-W3",
    "HiraMinProN-W6",
    "HoeflerText-Regular",
    "Kailasa",
    "Kefa-Regular",
    "KhmerSangamMN",
    "KohinoorBangla-Regular",
    "KohinoorDevanagari-Regular",
    "KohinoorGujarati-Regular",
    "KohinoorTelugu-Regular",
    "LaoSangamMN",
    "Lora-Regular",
    "MalayalamSangamMN",
    "MarkerFelt-Thin",
    "Menlo-Regular",
    "MuktaMahee-Regular",
    "MyanmarSangamMN",
    "Noteworthy-Light",
    "NotoNastaliqUrdu",
    "NotoSansKannada-Regular",
    "NotoSansMyanmar-Regular",
    "NotoSansOriya",
    "Optima-Regular",
    "Palatino-Roman",
    "Papyrus",
    "PartyLetPlain",
    "PingFangHK-Regular",
    "PingFangSC-Regular",
    "PingFangTC-Regular",
    "Rockwell-Regular",
    "SavoyeLetPlain",
    "SinhalaSangamMN",
    "SnellRoundhand",
    "Symbol",
    "TamilSangamMN",
    "Thonburi",
    "TimesNewRomanPSMT",
    "TrebuchetMS",
    "Verdana",
    "ZapfDingbatsITC",
    "Zapfino",
]
